/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package springcheckfornulltest;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class App {
    public static void main(String[] args) {
        ApplicationContext ctx = new AnnotationConfigApplicationContext(Config.class);
        TakingOptionalParams obj = ctx.getBean(TakingOptionalParams.class);
        System.out.println("obj.times10(13) is " + obj.times10(13));
    }
}
